# Data Cleaning & Preprocessing

**Handling missing values, duplicates,
inconsistent formats, and feature engineering**

In [1]:
import pandas as pd

df = pd.read_csv("books_raw.csv")

df.head()

,Title,Price,Rating,Availability,URL
0,A Light in the Attic,Â£51.77,Three,In stock,a-light-in-the-attic_1000/index.html
1,Tipping the Velvet,Â£53.74,One,In stock,tipping-the-velvet_999/index.html
2,Soumission,Â£50.10,One,In stock,soumission_998/index.html
3,Sharp Objects,Â£47.82,Four,In stock,sharp-objects_997/index.html
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,sapiens-a-brief-history-of-humankind_996/index...

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1000
Columns: 5

In [4]:
df.columns

Index(['Title', 'Price', 'Rating', 'Availability', 'URL'], dtype='object')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         1000 non-null   object
 1   price         1000 non-null   object
 2   rating        1000 non-null   object
 3   availability  1000 non-null   object
 4   url           1000 non-null   object
 5   price_clean   0 non-null      float64
dtypes: float64(1), object(5)
memory usage: 47.0+ KB

In [6]:
df.describe(include="all")

,Title,Price,Rating,Availability,URL
count,1000,1000,1000,1000,1000
unique,999,903,5,1,1000
top,The Star-Touched Queen,Â£37.34,One,In stock,1000-places-to-see-before-you-die_1/index.html
freq,2,3,226,1000,1

In [7]:
df.isnull().sum()

Title           0
Price           0
Rating          0
Availability    0
URL             0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["Title"].duplicated().sum()

np.int64(1)

In [10]:
df = df.drop_duplicates()

In [11]:
print(df.shape)

(1000, 5)

In [12]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [39]:
df["price_clean"] = (
    df["price"]
    .astype(str)
    .str.replace("Â£", "", regex=False)
    .str.strip()
)

In [40]:
print(df[["price", "price_clean"]].head(10))

     price price_clean
0  Â£51.77       51.77
1  Â£53.74       53.74
2  Â£50.10       50.10
3  Â£47.82       47.82
4  Â£54.23       54.23
5  Â£22.65       22.65
6  Â£33.34       33.34
7  Â£17.93       17.93
8  Â£22.60       22.60
9  Â£52.15       52.15

In [41]:
df["price_clean"] = pd.to_numeric(
    df["price_clean"],
    errors="coerce"
)

In [42]:
print(df[["price", "price_clean"]].head(10))

     price  price_clean
0  Â£51.77        51.77
1  Â£53.74        53.74
2  Â£50.10        50.10
3  Â£47.82        47.82
4  Â£54.23        54.23
5  Â£22.65        22.65
6  Â£33.34        33.34
7  Â£17.93        17.93
8  Â£22.60        22.60
9  Â£52.15        52.15

In [43]:
print(df["price_clean"].isnull().sum())

0

In [44]:
print(df["price_clean"].dtype)

float64

In [46]:
print(df["rating"].unique())

['Three' 'One' 'Four' 'Five' 'Two']

In [47]:
rating_mapping = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

In [48]:
df["rating_numeric"] = df["rating"].map(rating_mapping)

In [49]:
df[["rating", "rating_numeric"]].head(10)

  rating  rating_numeric
0  Three               3
1    One               1
2    One               1
3   Four               4
4   Five               5
5    One               1
6   Four               4
7  Three               3
8   Four               4
9    One               1

In [50]:
print(df["rating_numeric"].isnull().sum())

0

In [51]:
print(df[df["rating_numeric"].isnull()][["rating", "rating_numeric"]])

Empty DataFrame
Columns: [rating, rating_numeric]
Index: []

In [52]:
print(df["rating"].unique())

['Three' 'One' 'Four' 'Five' 'Two']

In [53]:
df["rating_numeric"].value_counts().sort_index()

rating_numeric
1    226
2    196
3    203
4    179
5    196
Name: count, dtype: int64

In [54]:
print(df["rating_numeric"].isnull().sum())

0

In [55]:
print(df["availability"].unique())

['In stock']

In [56]:
df["availability"] = (
    df["availability"]
    .str.strip()
    .str.lower()
)

In [57]:
df["availability"].value_counts()

availability
in stock    1000
Name: count, dtype: int64

In [58]:
df.isnull().sum()

title             0
price             0
rating            0
availability      0
url               0
price_clean       0
rating_numeric    0
dtype: int64

In [59]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [60]:
print("Duplicate URLs:", df["url"].duplicated().sum())

Duplicate URLs: 0

In [61]:
print("Duplicate titles:", df["title"].duplicated().sum())

Duplicate titles: 1

In [62]:
df[df["title"].duplicated(keep=False)]

,title,price,rating,availability,url,price_clean,rating_numeric
236,The Star-Touched Queen,Â£46.02,Five,in stock,the-star-touched-queen_764/index.html,46.02,5
358,The Star-Touched Queen,Â£32.30,Five,in stock,the-star-touched-queen_642/index.html,32.30,5

In [63]:
print("Duplicate complete rows:", df.duplicated().sum())

Duplicate complete rows: 0

In [64]:
print("Duplicate URLs:", df["url"].duplicated().sum())

Duplicate URLs: 0

In [65]:
print("Minimum price:", df["price_clean"].min())
print("Maximum price:", df["price_clean"].max())

Minimum price: 10.0
Maximum price: 59.99

In [66]:
def price_category(price):
    if price < 20:
        return "Low"
    elif price < 40:
        return "Medium"
    else:
        return "High"

In [67]:
df["price_category"] = df["price_clean"].apply(price_category)

In [68]:
df[["price_clean", "price_category"]].head(10)

   price_clean price_category
0        51.77           High
1        53.74           High
2        50.10           High
3        47.82           High
4        54.23           High
5        22.65         Medium
6        33.34         Medium
7        17.93            Low
8        22.60         Medium
9        52.15           High

In [69]:
df["price_category"].value_counts()

price_category
High      403
Medium    401
Low       196
Name: count, dtype: int64

In [70]:
def rating_category(rating):
    if rating >= 4:
        return "Highly Rated"
    elif rating >= 3:
        return "Average"
    else:
        return "Low Rated"

In [71]:
df["rating_category"] = df["rating_numeric"].apply(rating_category)

In [72]:
df[["rating_numeric", "rating_category"]].head(10)

   rating_numeric rating_category
0               3         Average
1               1       Low Rated
2               1       Low Rated
3               4    Highly Rated
4               5    Highly Rated
5               1       Low Rated
6               4    Highly Rated
7               3         Average
8               4    Highly Rated
9               1       Low Rated

In [73]:
df["rating_category"].value_counts()

rating_category
Low Rated       422
Highly Rated    375
Average         203
Name: count, dtype: int64

In [74]:
print(df["price_category"].isnull().sum())
print(df["rating_category"].isnull().sum())

0
0

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            1000 non-null   object
 1   price            1000 non-null   object
 2   rating           1000 non-null   object
 3   availability     1000 non-null   object
 4   url              1000 non-null   object
 5   price_clean      1000 non-null   float64
 6   rating_numeric   1000 non-null   int64
 7   price_category   1000 non-null   object
 8   rating_category  1000 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 70.4+ KB

In [76]:
print("Rows:", len(df))
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate URLs:", df["url"].duplicated().sum())

Rows: 1000
Missing values: 0
Duplicate rows: 0
Duplicate URLs: 0

In [78]:
df.to_csv("books_cleaned.csv", index=False)